/*
 * One-time Password Service
 *
 * One time password service built in Goglang that uses redis for keystore and can get user information from mongo or postgres.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// OtpSession - An OTP session with all channels supported that user can choose from.
type OtpSession struct {

	// an ID generated for this new OTP session.
	Id string `json:"id"`

	// List of channels that are supported
	Channels []Channel `json:"channels"`
}
