/*
 * One-time Password Service
 *
 * One time password service built in Goglang that uses redis for keystore and can get user information from mongo or postgres.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type Channel struct {

	Id string `json:"id"`

	Name string `json:"name"`

	ObfuscatedValue string `json:"obfuscatedValue"`

	// default: false, when this validateChannel is true, UI must ask for the full value such as full email or the full phone number. This value needs to be presented in the body of sendOTP API request. The server will valiadte the channel name and send the OTP only if the channel ID works.
	ValidateChannel bool `json:"validateChannel,omitempty"`
}
