secretsfile: "./config/.secrets.yaml"
scenarios:
  # login scenario
  loginauth:
    ttl: 100
    keywithalpha: false
    numattempts: 2
    allowtext: true
# uncomment line below if you want a leading text to be added to the OTP string.
#    leadingtext: "boo-"
    phonestorecfg:
      storetype: "mongo"
      storeid: "018d0df5-a50d-7017-883b-8431e708d4b2"
  pwdreset:
    ttl: 100
    keywithalpha: false
    numattempts: 2
    allowemail: true
    allowtext: true
    leadingtext: "pwd-"
mongostores:
  - id: "018d0df5-a50d-7017-883b-8431e708d4b2"
    database: <DATABASE NAME>
    collection: <COLLECTION NAME>
    connectionurlenv: "MONGO_URL"
twilioconfig:
  accountidenv: TWILIO_ACCT_SID
  authtokenenv: TWILIO_AUTH_TOKEN
  phonenumber: <TWILIO PHONE NUMBER>